package com.androidforge.studio.data.template

import com.androidforge.studio.domain.model.Template

/**
 * Generates complete, buildable project file trees for every built-in template.
 * Files are returned as a map of relative path -> content.
 *
 * Generated projects target the same toolchain the on-device builder supports:
 * minSdk 26, compileSdk 35, AGP 8.7.x, Kotlin 2.1.x, Gradle Kotlin DSL.
 */
object TemplateEngine {

    fun generate(templateId: String, projectName: String, packageName: String): Map<String, String> {
        val template = Template.fromId(templateId)
        val files = commonFiles(projectName, packageName, template)
        val specific = when (template) {
            Template.EMPTY_COMPOSE -> emptyComposeFiles(packageName)
            Template.XML_LAYOUT -> xmlLayoutFiles(packageName)
            Template.FIREBASE -> firebaseFiles(packageName)
            Template.ECOMMERCE -> ecommerceFiles(packageName)
            Template.CHAT -> chatFiles(packageName)
            Template.GAME_2D -> game2dFiles(packageName)
        }
        return files + specific
    }

    // ---------------------------------------------------------------- common

    private fun commonFiles(projectName: String, packageName: String, template: Template): Map<String, String> {
        val pkgPath = packageName.replace('.', '/')
        return linkedMapOf(
            "settings.gradle.kts" to """
                rootProject.name = "$projectName"
                include(":app")
            """.trimIndent() + "\n",

            "build.gradle.kts" to """
                // Top-level build file.
                plugins {
                    id("com.android.application") version "8.7.3" apply false
                    id("org.jetbrains.kotlin.android") version "2.1.0" apply false
                    id("org.jetbrains.kotlin.plugin.compose") version "2.1.0" apply false
                }
            """.trimIndent() + "\n",

            "gradle.properties" to """
                org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
                android.useAndroidX=true
                kotlin.code.style=official
                android.nonTransitiveRClass=true
            """.trimIndent() + "\n",

            "gradle/wrapper/gradle-wrapper.properties" to """
                distributionBase=GRADLE_USER_HOME
                distributionPath=wrapper/dists
                distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-bin.zip
                zipStoreBase=GRADLE_USER_HOME
                zipStorePath=wrapper/dists
            """.trimIndent() + "\n",

            ".gitignore" to """
                *.iml
                .gradle
                /local.properties
                .idea
                build
                /captures
                .externalNativeBuild
                .cxx
                local.properties
            """.trimIndent() + "\n",

            "app/src/main/AndroidManifest.xml" to manifestXml(packageName),

            "app/src/main/res/values/strings.xml" to """
                <resources>
                    <string name="app_name">$projectName</string>
                </resources>
            """.trimIndent() + "\n",

            "app/src/main/res/values/colors.xml" to """
                <resources>
                    <color name="primary">#FF6D00</color>
                    <color name="primary_dark">#E65100</color>
                    <color name="white">#FFFFFF</color>
                    <color name="black">#000000</color>
                </resources>
            """.trimIndent() + "\n",

            "app/src/main/java/$pkgPath/README.md" to """
                # $projectName

                Generated by **AndroidForge Studio** from the `${template.title}` template.

                Package: `$packageName`
                Template: `${template.id}`

                ## Build

                * On device: open this project in AndroidForge Studio → **Build** tab → *Assemble APK*.
                * On desktop: `./gradlew assembleDebug` (requires JDK 17 + Android SDK 35).
            """.trimIndent() + "\n",
        )
    }

    private fun manifestXml(packageName: String): String = """
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">

            <application
                android:allowBackup="true"
                android:icon="@mipmap/ic_launcher"
                android:label="@string/app_name"
                android:supportsRtl="true"
                android:theme="@style/Theme.App">
                <activity
                    android:name=".MainActivity"
                    android:exported="true"
                    android:windowSoftInputMode="adjustResize">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>

        </manifest>
    """.trimIndent() + "\n"

    // ------------------------------------------------------------ app module

    private fun appGradle(packageName: String, compose: Boolean, extraDeps: List<String> = emptyList()): String {
        val composeBlock = if (compose) """
            buildFeatures { compose = true }
        """.trimIndent() else ""
        val deps = buildList {
            add("implementation(\"androidx.core:core-ktx:1.15.0\")")
            add("implementation(\"androidx.appcompat:appcompat:1.7.0\")")
            add("implementation(\"com.google.android.material:material:1.12.0\")")
            add("implementation(\"androidx.constraintlayout:constraintlayout:2.2.0\")")
            if (compose) {
                add("implementation(platform(\"androidx.compose:compose-bom:2024.12.01\"))")
                add("implementation(\"androidx.compose.ui:ui\")")
                add("implementation(\"androidx.compose.material3:material3\")")
                add("implementation(\"androidx.activity:activity-compose:1.9.3\")")
                add("implementation(\"androidx.lifecycle:lifecycle-runtime-ktx:2.8.7\")")
                add("implementation(\"androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7\")")
            }
            addAll(extraDeps)
            add("testImplementation(\"junit:junit:4.13.2\")")
        }.joinToString("\n") { "    $it" }

        return """
            plugins {
                id("com.android.application")
                id("org.jetbrains.kotlin.android")${if (compose) "\n    id(\"org.jetbrains.kotlin.plugin.compose\")" else ""}
            }

            android {
                namespace = "$packageName"
                compileSdk = 35

                defaultConfig {
                    applicationId = "$packageName"
                    minSdk = 26
                    targetSdk = 35
                    versionCode = 1
                    versionName = "1.0"
                }

                buildTypes {
                    release {
                        isMinifyEnabled = false
                        proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
                    }
                }
                compileOptions {
                    sourceCompatibility = JavaVersion.VERSION_17
                    targetCompatibility = JavaVersion.VERSION_17
                }
                kotlinOptions { jvmTarget = "17" }
                $composeBlock
            }

            dependencies {
            $deps
            }
        """.trimIndent() + "\n"
    }

    private fun appGradleFile(packageName: String, compose: Boolean, extraDeps: List<String> = emptyList()): Pair<String, String> =
        "app/build.gradle.kts" to appGradle(packageName, compose, extraDeps)

    private fun proguardFile(): Pair<String, String> =
        "app/proguard-rules.pro" to "# Add project specific ProGuard rules here.\n-keepattributes *Annotation*\n"

    private fun launcherManifestFix(): Pair<String, String> =
        "app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml" to """
            <?xml version="1.0" encoding="utf-8"?>
            <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
                <background android:drawable="@color/primary" />
                <foreground android:drawable="@android:drawable/sym_def_app_icon" />
            </adaptive-icon>
        """.trimIndent() + "\n"

    // ------------------------------------------------------ 1) Empty Compose

    private fun emptyComposeFiles(packageName: String): Map<String, String> {
        val pkgPath = packageName.replace('.', '/')
        return mapOf(
            appGradleFile(packageName, compose = true),
            proguardFile(),
            launcherManifestFix(),
            "app/src/main/java/$pkgPath/MainActivity.kt" to """
                package $packageName

                import android.os.Bundle
                import androidx.activity.ComponentActivity
                import androidx.activity.compose.setContent
                import androidx.compose.foundation.layout.Box
                import androidx.compose.foundation.layout.fillMaxSize
                import androidx.compose.foundation.layout.padding
                import androidx.compose.material3.MaterialTheme
                import androidx.compose.material3.Scaffold
                import androidx.compose.material3.Text
                import androidx.compose.material3.darkColorScheme
                import androidx.compose.material3.lightColorScheme
                import androidx.compose.runtime.Composable
                import androidx.compose.ui.Alignment
                import androidx.compose.ui.Modifier
                import androidx.compose.ui.tooling.preview.Preview
                import androidx.compose.foundation.isSystemInDarkTheme

                class MainActivity : ComponentActivity() {
                    override fun onCreate(savedInstanceState: Bundle?) {
                        super.onCreate(savedInstanceState)
                        setContent {
                            AppTheme {
                                MainScreen()
                            }
                        }
                    }
                }

                @Composable
                private fun AppTheme(content: @Composable () -> Unit) {
                    val colors = if (isSystemInDarkTheme()) darkColorScheme() else lightColorScheme()
                    MaterialTheme(colorScheme = colors, content = content)
                }

                @Composable
                fun MainScreen() {
                    Scaffold { padding ->
                        Box(
                            modifier = Modifier.fillMaxSize().padding(padding),
                            contentAlignment = Alignment.Center,
                        ) {
                            Text(text = "Hello from AndroidForge Studio!")
                        }
                    }
                }

                @Preview(showBackground = true)
                @Composable
                private fun MainScreenPreview() {
                    AppTheme { MainScreen() }
                }
            """.trimIndent() + "\n",
        )
    }

    // ---------------------------------------------------------- 2) XML Layout

    private fun xmlLayoutFiles(packageName: String): Map<String, String> {
        val pkgPath = packageName.replace('.', '/')
        return mapOf(
            appGradleFile(packageName, compose = false),
            proguardFile(),
            launcherManifestFix(),
            "app/src/main/res/layout/activity_main.xml" to """
                <?xml version="1.0" encoding="utf-8"?>
                <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:orientation="vertical"
                    android:gravity="center"
                    android:padding="24dp">

                    <TextView
                        android:id="@+id/title"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="XML Layout App"
                        android:textSize="24sp"
                        android:textStyle="bold" />

                    <Button
                        android:id="@+id/action"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="16dp"
                        android:text="Tap me" />
                </LinearLayout>
            """.trimIndent() + "\n",
            "app/src/main/res/values/themes.xml" to """
                <resources>
                    <style name="Theme.App" parent="Theme.Material3.DayNight.NoActionBar" />
                </resources>
            """.trimIndent() + "\n",
            "app/src/main/java/$pkgPath/MainActivity.kt" to """
                package $packageName

                import android.os.Bundle
                android.widget.Button
                android.widget.TextView
                android.widget.Toast
                import androidx.appcompat.app.AppCompatActivity

                class MainActivity : AppCompatActivity() {
                    override fun onCreate(savedInstanceState: Bundle?) {
                        super.onCreate(savedInstanceState)
                        setContentView(R.layout.activity_main)

                        val title = findViewById<TextView>(R.id.title)
                        val action = findViewById<Button>(R.id.action)
                        title.text = getString(R.string.app_name)
                        action.setOnClickListener {
                            Toast.makeText(this, "Hello from AndroidForge Studio!", Toast.LENGTH_SHORT).show()
                        }
                    }
                }
            """.trimIndent() + "\n",
        )
    }

    // ------------------------------------------------------------ 3) Firebase

    private fun firebaseFiles(packageName: String): Map<String, String> {
        val pkgPath = packageName.replace('.', '/')
        val base = emptyComposeFiles(packageName).toMutableMap()
        base[appGradleFile(packageName, compose = true).first] = appGradle(
            packageName,
            compose = true,
            extraDeps = listOf(
                "implementation(\"com.google.firebase:firebase-bom:33.7.0\")",
                "implementation(\"com.google.firebase:firebase-auth-ktx\")",
                "implementation(\"com.google.firebase:firebase-firestore-ktx\")",
            ),
        )
        base["app/google-services.json.example"] = """
            {
              "project_info": {
                "project_number": "000000000000",
                "project_id": "your-firebase-project",
                "storage_bucket": "your-firebase-project.appspot.com"
              },
              "client": [
                {
                  "client_info": {
                    "mobilesdk_app_id": "1:000000000000:android:0000000000000000",
                    "android_client_info": { "package_name": "$packageName" }
                  },
                  "api_key": [{ "current_key": "REPLACE_ME" }]
                }
              ],
              "configuration_version": "1"
            }
        """.trimIndent() + "\n"
        base["app/src/main/java/$pkgPath/data/UserRepository.kt"] = """
            package $packageName.data

            /**
             * Thin wrapper around Firebase Auth/Firestore.
             * Copy google-services.json.example -> google-services.json and add the
             * google-services plugin to app/build.gradle.kts to enable real calls.
             */
            class UserRepository {
                suspend fun greet(name: String): String = "Welcome, ${'$'}name!"
            }
        """.trimIndent() + "\n"
        return base
    }

    // ----------------------------------------------------------- 4) Ecommerce

    private fun ecommerceFiles(packageName: String): Map<String, String> {
        val pkgPath = packageName.replace('.', '/')
        return mapOf(
            appGradleFile(packageName, compose = true),
            proguardFile(),
            launcherManifestFix(),
            "app/src/main/java/$pkgPath/model/Product.kt" to """
                package $packageName.model

                data class Product(
                    val id: Long,
                    val name: String,
                    val priceCents: Int,
                    val emoji: String,
                ) {
                    val price: String get() = "$" + "%,.2f".format(priceCents / 100.0)
                }

                object SampleCatalog {
                    val products = listOf(
                        Product(1, "Forge Hammer", 2499, "\uD83D\uDD28"),
                        Product(2, "Anvil Stand", 8999, "\uD83D\uDDFF"),
                        Product(3, "Heat Gloves", 1599, "\uD83E\uDDE4"),
                        Product(4, "Steel Tongs", 1299, "\uD83E\uDE07"),
                        Product(5, "Apron Deluxe", 3499, "\uD83E\uDE77"),
                    )
                }
            """.trimIndent() + "\n",
            "app/src/main/java/$pkgPath/ui/ShopScreen.kt" to """
                package $packageName.ui

                import androidx.compose.foundation.layout.Arrangement
                import androidx.compose.foundation.layout.Column
                import androidx.compose.foundation.layout.PaddingValues
                import androidx.compose.foundation.layout.fillMaxSize
                import androidx.compose.foundation.layout.fillMaxWidth
                import androidx.compose.foundation.layout.padding
                import androidx.compose.foundation.lazy.LazyColumn
                import androidx.compose.foundation.lazy.items
                import androidx.compose.material3.Card
                import androidx.compose.material3.ExperimentalMaterial3Api
                import androidx.compose.material3.MaterialTheme
                import androidx.compose.material3.Scaffold
                import androidx.compose.material3.Text
                import androidx.compose.material3.TopAppBar
                import androidx.compose.runtime.Composable
                import androidx.compose.ui.Modifier
                import androidx.compose.ui.unit.dp
                import $packageName.model.Product
                import $packageName.model.SampleCatalog

                @OptIn(ExperimentalMaterial3Api::class)
                @Composable
                fun ShopScreen() {
                    Scaffold(
                        topBar = { TopAppBar(title = { Text("Forge Shop") }) },
                    ) { padding ->
                        LazyColumn(
                            modifier = Modifier.fillMaxSize().padding(padding),
                            contentPadding = PaddingValues(16.dp),
                            verticalArrangement = Arrangement.spacedBy(12.dp),
                        ) {
                            items(SampleCatalog.products) { product -> ProductCard(product) }
                        }
                    }
                }

                @Composable
                private fun ProductCard(product: Product) {
                    Card(modifier = Modifier.fillMaxWidth()) {
                        Column(modifier = Modifier.padding(16.dp)) {
                            Text(text = "${'$'}{product.emoji} ${'$'}{product.name}", style = MaterialTheme.typography.titleMedium)
                            Text(text = product.price, style = MaterialTheme.typography.bodyMedium)
                        }
                    }
                }
            """.trimIndent() + "\n",
            "app/src/main/java/$pkgPath/MainActivity.kt" to """
                package $packageName

                import android.os.Bundle
                import androidx.activity.ComponentActivity
                import androidx.activity.compose.setContent
                import androidx.compose.material3.MaterialTheme
                import $packageName.ui.ShopScreen

                class MainActivity : ComponentActivity() {
                    override fun onCreate(savedInstanceState: Bundle?) {
                        super.onCreate(savedInstanceState)
                        setContent { MaterialTheme { ShopScreen() } }
                    }
                }
            """.trimIndent() + "\n",
        )
    }

    // ---------------------------------------------------------------- 5) Chat

    private fun chatFiles(packageName: String): Map<String, String> {
        val pkgPath = packageName.replace('.', '/')
        return mapOf(
            appGradleFile(packageName, compose = true),
            proguardFile(),
            launcherManifestFix(),
            "app/src/main/java/$pkgPath/model/Message.kt" to """
                package $packageName.model

                data class Message(
                    val id: Long,
                    val fromMe: Boolean,
                    val text: String,
                    val time: String,
                )
            """.trimIndent() + "\n",
            "app/src/main/java/$pkgPath/ui/ChatScreen.kt" to """
                package $packageName.ui

                import androidx.compose.foundation.background
                import androidx.compose.foundation.layout.Arrangement
                import androidx.compose.foundation.layout.Box
                import androidx.compose.foundation.layout.Column
                import androidx.compose.foundation.layout.Row
                import androidx.compose.foundation.layout.fillMaxSize
                import androidx.compose.foundation.layout.fillMaxWidth
                import androidx.compose.foundation.layout.padding
                import androidx.compose.foundation.layout.widthIn
                import androidx.compose.foundation.lazy.LazyColumn
                import androidx.compose.foundation.lazy.items
                import androidx.compose.foundation.lazy.rememberLazyListState
                import androidx.compose.foundation.shape.RoundedCornerShape
                import androidx.compose.material3.Button
                import androidx.compose.material3.ExperimentalMaterial3Api
                import androidx.compose.material3.MaterialTheme
                import androidx.compose.material3.OutlinedTextField
                import androidx.compose.material3.Scaffold
                import androidx.compose.material3.Text
                import androidx.compose.material3.TopAppBar
                import androidx.compose.runtime.Composable
                import androidx.compose.runtime.getValue
                import androidx.compose.runtime.mutableStateListOf
                import androidx.compose.runtime.mutableStateOf
                import androidx.compose.runtime.remember
                import androidx.compose.runtime.setValue
                import androidx.compose.ui.Alignment
                import androidx.compose.ui.Modifier
                import androidx.compose.ui.graphics.Color
                import androidx.compose.ui.unit.dp
                import $packageName.model.Message
                import java.text.SimpleDateFormat
                import java.util.Date
                import java.util.Locale

                @OptIn(ExperimentalMaterial3Api::class)
                @Composable
                fun ChatScreen() {
                    val messages = remember {
                        mutableStateListOf(
                            Message(1, false, "Hey! Welcome to the forge 🔥", "09:41"),
                            Message(2, true, "Thanks, this editor is fast.", "09:42"),
                        )
                    }
                    var draft by remember { mutableStateOf("") }
                    val listState = rememberLazyListState()

                    Scaffold(
                        topBar = { TopAppBar(title = { Text("Forge Chat") }) },
                    ) { padding ->
                        Column(modifier = Modifier.fillMaxSize().padding(padding)) {
                            LazyColumn(
                                state = listState,
                                modifier = Modifier.weight(1f).fillMaxWidth(),
                                contentPadding = androidx.compose.foundation.layout.PaddingValues(16.dp),
                                verticalArrangement = Arrangement.spacedBy(8.dp),
                            ) {
                                items(messages) { msg -> Bubble(msg) }
                            }
                            Row(
                                modifier = Modifier.fillMaxWidth().padding(8.dp),
                                verticalAlignment = Alignment.CenterVertically,
                            ) {
                                OutlinedTextField(
                                    value = draft,
                                    onValueChange = { draft = it },
                                    modifier = Modifier.weight(1f),
                                    placeholder = { Text("Message…") },
                                )
                                Button(
                                    onClick = {
                                        if (draft.isNotBlank()) {
                                            val now = SimpleDateFormat("HH:mm", Locale.getDefault()).format(Date())
                                            messages.add(Message(System.nanoTime(), true, draft.trim(), now))
                                            draft = ""
                                        }
                                    },
                                    modifier = Modifier.padding(start = 8.dp),
                                ) { Text("Send") }
                            }
                        }
                    }
                }

                @Composable
                private fun Bubble(msg: Message) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = if (msg.fromMe) Arrangement.End else Arrangement.Start,
                    ) {
                        Box(
                            modifier = Modifier
                                .background(
                                    color = if (msg.fromMe) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.surfaceVariant,
                                    shape = RoundedCornerShape(16.dp),
                                )
                                .widthIn(max = 280.dp)
                                .padding(horizontal = 14.dp, vertical = 10.dp),
                        ) {
                            Column {
                                Text(
                                    text = msg.text,
                                    color = if (msg.fromMe) Color.White else MaterialTheme.colorScheme.onSurface,
                                )
                                Text(
                                    text = msg.time,
                                    style = MaterialTheme.typography.labelSmall,
                                    color = if (msg.fromMe) Color.White.copy(alpha = 0.7f) else MaterialTheme.colorScheme.outline,
                                )
                            }
                        }
                    }
                }
            """.trimIndent() + "\n",
            "app/src/main/java/$pkgPath/MainActivity.kt" to """
                package $packageName

                import android.os.Bundle
                import androidx.activity.ComponentActivity
                import androidx.activity.compose.setContent
                import androidx.compose.material3.MaterialTheme
                import $packageName.ui.ChatScreen

                class MainActivity : ComponentActivity() {
                    override fun onCreate(savedInstanceState: Bundle?) {
                        super.onCreate(savedInstanceState)
                        setContent { MaterialTheme { ChatScreen() } }
                    }
                }
            """.trimIndent() + "\n",
        )
    }

    // ------------------------------------------------------------- 6) 2D Game

    private fun game2dFiles(packageName: String): Map<String, String> {
        val pkgPath = packageName.replace('.', '/')
        return mapOf(
            appGradleFile(packageName, compose = true),
            proguardFile(),
            launcherManifestFix(),
            "app/src/main/java/$pkgPath/ui/GameScreen.kt" to """
                package $packageName.ui

                import androidx.compose.foundation.Canvas
                import androidx.compose.foundation.gestures.detectTapGestures
                import androidx.compose.foundation.layout.Box
                import androidx.compose.foundation.layout.fillMaxSize
                import androidx.compose.foundation.layout.padding
                import androidx.compose.material3.MaterialTheme
                import androidx.compose.material3.Text
                import androidx.compose.runtime.Composable
                import androidx.compose.runtime.LaunchedEffect
                import androidx.compose.runtime.getValue
                import androidx.compose.runtime.mutableFloatStateOf
                import androidx.compose.runtime.mutableLongStateOf
                import androidx.compose.runtime.mutableStateOf
                import androidx.compose.runtime.remember
                import androidx.compose.runtime.setValue
                import androidx.compose.ui.Alignment
                import androidx.compose.ui.Modifier
                import androidx.compose.ui.geometry.Offset
                import androidx.compose.ui.graphics.Color
                import androidx.compose.ui.input.pointer.pointerInput
                import androidx.compose.ui.unit.dp
                import androidx.compose.ui.unit.sp
                import kotlinx.coroutines.delay

                @Composable
                fun GameScreen() {
                    var target by remember { mutableStateOf(Offset(300f, 600f)) }
                    var score by remember { mutableLongStateOf(0L) }
                    var misses by remember { mutableLongStateOf(0L) }
                    var running by remember { mutableStateOf(true) }

                    // Game loop: relocate the target every 900ms.
                    LaunchedEffect(running, score) {
                        while (running) {
                            delay(900)
                            // keep target inside a safe playfield (updated by canvas size below)
                        }
                    }

                    Box(
                        modifier = Modifier
                            .fillMaxSize()
                            .pointerInput(Unit) {
                                detectTapGestures { pos ->
                                    val dx = pos.x - target.x
                                    val dy = pos.y - target.y
                                    if (dx * dx + dy * dy < 90f * 90f) {
                                        score += 1
                                        target = Offset(
                                            (50..(size.width - 50)).random().toFloat(),
                                            (150..(size.height - 150)).random().toFloat(),
                                        )
                                    } else {
                                        misses += 1
                                    }
                                }
                            },
                        contentAlignment = Alignment.TopCenter,
                    ) {
                        Canvas(modifier = Modifier.fillMaxSize()) {
                            drawCircle(color = Color(0xFFFF6D00), radius = 60f, center = target)
                            drawCircle(color = Color.White, radius = 70f, center = target, style = androidx.compose.ui.graphics.drawscope.Stroke(width = 4f))
                        }
                        Text(
                            text = "Score: ${'$'}score   Misses: ${'$'}misses",
                            fontSize = 20.sp,
                            color = Color.White,
                            modifier = Modifier.padding(top = 24.dp),
                        )
                    }
                }
            """.trimIndent() + "\n",
            "app/src/main/java/$pkgPath/MainActivity.kt" to """
                package $packageName

                import android.os.Bundle
                import androidx.activity.ComponentActivity
                import androidx.activity.compose.setContent
                import androidx.compose.material3.MaterialTheme
                import androidx.compose.material3.darkColorScheme
                import $packageName.ui.GameScreen

                class MainActivity : ComponentActivity() {
                    override fun onCreate(savedInstanceState: Bundle?) {
                        super.onCreate(savedInstanceState)
                        setContent { MaterialTheme(colorScheme = darkColorScheme()) { GameScreen() } }
                    }
                }
            """.trimIndent() + "\n",
        )
    }
}
