package com.androidforge.studio.ui.builder

import androidx.compose.ui.graphics.Color
import com.androidforge.studio.domain.model.CodeLanguage

/** A node in the visual layout being built. */
data class UiComponent(
    val id: String,
    val type: ComponentType,
    val props: Map<String, String> = emptyMap(),
    val children: List<UiComponent> = emptyList(),
) {
    val text: String get() = props["text"] ?: ""
}

enum class ComponentType(
    val displayName: String,
    val category: String,
    val acceptsChildren: Boolean,
) {
    COLUMN("Column", "Layout", true),
    ROW("Row", "Layout", true),
    BOX("Box", "Layout", true),
    SPACER("Spacer", "Layout", false),
    TEXT("Text", "Content", false),
    BUTTON("Button", "Input", true),
    IMAGE("Image", "Media", false),
    TEXTFIELD("TextField", "Input", false),
    CARD("Card", "Container", true),
    DIVIDER("Divider", "Content", false),
    ICON("Icon", "Media", false),
    LIST("LazyColumn", "Layout", true);

    val isContainer: Boolean get() = acceptsChildren
}

/** Palette entry shown in the component drawer. */
data class PaletteItem(val type: ComponentType)

val defaultPalette: List<PaletteItem> = ComponentType.entries.map { PaletteItem(it) }

/** Builds a new component with sensible defaults. */
fun newComponent(type: ComponentType, id: String): UiComponent = UiComponent(
    id = id,
    type = type,
    props = when (type) {
        ComponentType.TEXT -> mapOf("text" to "Hello", "size" to "16")
        ComponentType.BUTTON -> mapOf("text" to "Button")
        ComponentType.TEXTFIELD -> mapOf("hint" to "Enter text…")
        ComponentType.ICON -> mapOf("icon" to "★")
        ComponentType.SPACER -> mapOf("height" to "16")
        ComponentType.IMAGE -> mapOf("contentDescription" to "image", "shape" to "rounded")
        else -> emptyMap()
    },
)

/** Generates Kotlin/Compose source from the component tree. */
object ComposeCodeGenerator {

    fun generate(root: UiComponent, functionName: String = "GeneratedScreen"): String = buildString {
        appendLine("// Generated by AndroidForge Studio UI Builder")
        appendLine("import androidx.compose.foundation.background")
        appendLine("import androidx.compose.foundation.layout.*")
        appendLine("import androidx.compose.material3.*")
        appendLine("import androidx.compose.runtime.Composable")
        appendLine("import androidx.compose.ui.Modifier")
        appendLine("import androidx.compose.ui.unit.dp")
        appendLine("import androidx.compose.ui.unit.sp")
        appendLine()
        appendLine("@Composable")
        appendLine("fun $functionName() {")
        emit(root, indent = 1)
        appendLine("}")
    }

    private fun StringBuilder.emit(c: UiComponent, indent: Int) {
        val pad = "    ".repeat(indent)
        when (c.type) {
            ComponentType.COLUMN -> {
                appendLine("$padColumn(modifier = ${modifierString(c)}) {")
                emitChildren(c, indent + 1)
                appendLine("$pad}")
            }
            ComponentType.ROW -> {
                appendLine("$padRow(modifier = ${modifierString(c)}) {")
                emitChildren(c, indent + 1)
                appendLine("$pad}")
            }
            ComponentType.BOX -> {
                appendLine("$padBox(modifier = ${modifierString(c)}) {")
                emitChildren(c, indent + 1)
                appendLine("$pad}")
            }
            ComponentType.TEXT -> {
                val size = c.props["size"] ?: "16"
                appendLine("$padText(text = \"${c.text}\", fontSize = ${size}.sp)")
            }
            ComponentType.BUTTON -> {
                appendLine("$padButton(onClick = { /* TODO */ }) {")
                appendLine("${pad}    Text(\"${c.text.ifBlank { "Button" }}\")")
                appendLine("$pad}")
                emitChildren(c, indent + 1)
            }
            ComponentType.TEXTFIELD -> {
                appendLine("$padOutlinedTextField(")
                appendLine("${pad}    value = \"\",")
                appendLine("${pad}    onValueChange = { },")
                appendLine("${pad}    placeholder = { Text(\"${c.props["hint"] ?: ""}\") },")
                appendLine("${pad}    modifier = ${modifierString(c)}.fillMaxWidth(),")
                appendLine("$pad)")
            }
            ComponentType.CARD -> {
                appendLine("$padCard(modifier = ${modifierString(c)}) {")
                emitChildren(c, indent + 1)
                appendLine("$pad}")
            }
            ComponentType.SPACER -> {
                appendLine("$padSpacer(Modifier.height(${c.props["height"] ?: "16"}.dp))")
            }
            ComponentType.DIVIDER -> {
                appendLine("$padHorizontalDivider()")
            }
            ComponentType.ICON -> {
                appendLine("$padText(\"${c.props["icon"] ?: "•"}\", fontSize = 24.sp)")
            }
            ComponentType.IMAGE -> {
                appendLine("$padText(\"[Image: ${c.props["contentDescription"] ?: "image"}]\") // replace with AsyncImage")
            }
            ComponentType.LIST -> {
                appendLine("$padLazyColumn {")
                emitChildren(c, indent + 1)
                appendLine("$pad}")
            }
        }
    }

    private fun StringBuilder.emitChildren(c: UiComponent, indent: Int) {
        for (child in c.children) emit(child, indent)
    }

    private fun modifierString(c: UiComponent): String {
        val parts = mutableListOf<String>()
        val padding = c.props["padding"]
        if (padding != null) parts += "padding(${padding}.dp)"
        val bg = c.props["background"]
        if (bg != null) parts += "background(color = androidx.compose.ui.graphics.Color(0xFF$bg))"
        val w = c.props["width"]
        if (w == "match") parts += "fillMaxWidth()"
        return if (parts.isEmpty()) "Modifier" else "Modifier." + parts.joinToString(".")
    }
}

/** Generates a legacy XML layout from the component tree (best-effort mapping). */
object XmlCodeGenerator {

    fun generate(root: UiComponent, rootName: String = "root"): String = buildString {
        appendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
        emit(root, 0, isRoot = true)
    }

    private fun StringBuilder.emit(c: UiComponent, depth: Int, isRoot: Boolean) {
        val pad = "    ".repeat(depth)
        val lp = if (isRoot) "match_parent" else (c.props["width"] ?: "wrap_content").let {
            if (it == "match") "match_parent" else "${it}dp"
        }
        val hp = (c.props["height"] ?: "wrap_content").let {
            if (it == "match") "match_parent" else if (it == "wrap") "wrap_content" else "${it}dp"
        }
        val hasChildren = c.children.isNotEmpty()
        when (c.type) {
            ComponentType.COLUMN, ComponentType.LIST -> {
                appendLine("$pad<LinearLayout")
                appendLine("${pad}    android:layout_width=\"$lp\"")
                appendLine("${pad}    android:layout_height=\"$hp\"")
                appendLine("${pad}    android:orientation=\"vertical\">")
                for (ch in c.children) emit(ch, depth + 1, false)
                appendLine("$pad</LinearLayout>")
            }
            ComponentType.ROW -> {
                appendLine("$pad<LinearLayout")
                appendLine("${pad}    android:layout_width=\"$lp\"")
                appendLine("${pad}    android:layout_height=\"$hp\"")
                appendLine("${pad}    android:orientation=\"horizontal\">")
                for (ch in c.children) emit(ch, depth + 1, false)
                appendLine("$pad</LinearLayout>")
            }
            ComponentType.BOX -> {
                appendLine("$pad<FrameLayout")
                appendLine("${pad}    android:layout_width=\"$lp\"")
                appendLine("${pad}    android:layout_height=\"$hp\">")
                for (ch in c.children) emit(ch, depth + 1, false)
                appendLine("$pad</FrameLayout>")
            }
            ComponentType.TEXT -> {
                appendLine("$pad<TextView")
                appendLine("${pad}    android:layout_width=\"wrap_content\"")
                appendLine("${pad}    android:layout_height=\"wrap_content\"")
                appendLine("${pad}    android:text=\"${c.text}\"")
                appendLine("${pad}    android:textSize=\"${c.props["size"] ?: "16"}sp\" />")
            }
            ComponentType.BUTTON -> {
                appendLine("$pad<Button")
                appendLine("${pad}    android:layout_width=\"wrap_content\"")
                appendLine("${pad}    android:layout_height=\"wrap_content\"")
                appendLine("${pad}    android:text=\"${c.text.ifBlank { "Button" }}\" />")
                for (ch in c.children) emit(ch, depth + 1, false)
            }
            ComponentType.TEXTFIELD -> {
                appendLine("$pad<EditText")
                appendLine("${pad}    android:layout_width=\"match_parent\"")
                appendLine("${pad}    android:layout_height=\"wrap_content\"")
                appendLine("${pad}    android:hint=\"${c.props["hint"] ?: ""}\" />")
            }
            ComponentType.CARD -> {
                appendLine("$pad<androidx.cardview.widget.CardView")
                appendLine("${pad}    android:layout_width=\"$lp\"")
                appendLine("${pad}    android:layout_height=\"$hp\">")
                appendLine("$pad    <LinearLayout android:layout_width=\"match_parent\" android:layout_height=\"wrap_content\" android:orientation=\"vertical\">")
                for (ch in c.children) emit(ch, depth + 2, false)
                appendLine("$pad    </LinearLayout>")
                appendLine("$pad</androidx.cardview.widget.CardView>")
            }
            ComponentType.SPACER -> {
                appendLine("$pad<View")
                appendLine("${pad}    android:layout_width=\"match_parent\"")
                appendLine("${pad}    android:layout_height=\"${c.props["height"] ?: "16"}dp\" />")
            }
            ComponentType.DIVIDER -> {
                appendLine("$pad<View")
                appendLine("${pad}    android:layout_width=\"match_parent\"")
                appendLine("${pad}    android:layout_height=\"1dp\"")
                appendLine("${pad}    android:background=\"#33FFFFFF\" />")
            }
            ComponentType.ICON -> {
                appendLine("$pad<TextView")
                appendLine("${pad}    android:layout_width=\"wrap_content\"")
                appendLine("${pad}    android:layout_height=\"wrap_content\"")
                appendLine("${pad}    android:text=\"${c.props["icon"] ?: "•"}\" />")
            }
            ComponentType.IMAGE -> {
                appendLine("$pad<ImageView")
                appendLine("${pad}    android:layout_width=\"wrap_content\"")
                appendLine("${pad}    android:layout_height=\"wrap_content\"")
                appendLine("${pad}    android:contentDescription=\"${c.props["contentDescription"] ?: ""}\" />")
            }
        }
        if (isRoot && !hasChildren) {
            // root emitted already
        }
    }
}

/** Parses a generated/edited XML layout back into a component tree (subset). */
object LayoutParser {
    fun parse(xml: String): UiComponent? {
        // Minimal tag scanner good enough for layouts this app generates.
        val rootTag = Regex("""<(\w+)""").find(xml)?.groupValues?.get(1) ?: return null
        val rootType = when (rootTag) {
            "LinearLayout" -> if (xml.contains("horizontal")) ComponentType.ROW else ComponentType.COLUMN
            "FrameLayout" -> ComponentType.BOX
            "TextView" -> ComponentType.TEXT
            "Button" -> ComponentType.BUTTON
            else -> ComponentType.COLUMN
        }
        val text = Regex("""android:text="([^"]*)"""").find(xml)?.groupValues?.get(1) ?: ""
        return UiComponent(
            id = "root",
            type = rootType,
            props = if (text.isNotEmpty()) mapOf("text" to text) else emptyMap(),
            children = parseChildren(xml),
        )
    }

    private fun parseChildren(xml: String): List<UiComponent> {
        val children = mutableListOf<UiComponent>()
        var i = 0
        var idx = 0
        while (true) {
            val open = xml.indexOf('<', i)
            if (open < 0) break
            if (xml.startsWith("</", open)) { i = open + 2; continue }
            val close = xml.indexOf('>', open)
            if (close < 0) break
            val selfClosing = xml[close - 1] == '/'
            val tag = xml.substring(open + 1, close).trim().substringBefore(' ').substringBefore('\n')
            if (tag in setOf("TextView", "Button", "EditText", "View", "ImageView")) {
                val text = xml.substring(open, close + 1)
                    .let { Regex("""android:text="([^"]*)"""").find(it)?.groupValues?.get(1) ?: "" }
                val type = when (tag) {
                    "TextView" -> ComponentType.TEXT
                    "Button" -> ComponentType.BUTTON
                    "EditText" -> ComponentType.TEXTFIELD
                    "View" -> ComponentType.SPACER
                    else -> ComponentType.IMAGE
                }
                children += UiComponent(
                    id = "c${idx++}",
                    type = type,
                    props = if (text.isNotEmpty()) mapOf("text" to text) else emptyMap(),
                )
            } else if (tag in setOf("LinearLayout", "FrameLayout", "androidx.cardview.widget.CardView")) {
                children += UiComponent(
                    id = "c${idx++}",
                    type = when {
                        tag == "FrameLayout" -> ComponentType.BOX
                        tag.contains("CardView") -> ComponentType.CARD
                        xml.substring(open, close).contains("horizontal") -> ComponentType.ROW
                        else -> ComponentType.COLUMN
                    },
                )
            }
            i = close + 1
            if (selfClosing) continue
        }
        return children
    }
}

/** Maps a component type to a preview composable color for the canvas. */
fun previewColor(type: ComponentType): Color = when (type) {
    ComponentType.COLUMN -> Color(0xFF1F6FEB).copy(alpha = 0.25f)
    ComponentType.ROW -> Color(0xFF238636).copy(alpha = 0.25f)
    ComponentType.BOX -> Color(0xFF8957E5).copy(alpha = 0.25f)
    ComponentType.TEXT -> Color(0xFFFF6D00).copy(alpha = 0.20f)
    ComponentType.BUTTON -> Color(0xFFFFB74D).copy(alpha = 0.35f)
    ComponentType.TEXTFIELD -> Color(0xFF1DE9B6).copy(alpha = 0.20f)
    ComponentType.CARD -> Color(0xFF40C4FF).copy(alpha = 0.20f)
    ComponentType.LIST -> Color(0xFFDB61A2).copy(alpha = 0.20f)
    else -> Color(0xFF8B949E).copy(alpha = 0.15f)
}

/** Language used when exporting the current design to a project file. */
fun exportLanguageFor(isXml: Boolean): CodeLanguage =
    if (isXml) CodeLanguage.XML else CodeLanguage.KOTLIN
